# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LottieTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'lottie-ios'
  # Pods for LottieTest

  target 'LottieTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LottieTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
